export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAIL = "SEARCH_FAIL";
export const CLEAR_SEARCH = "CLEAR_SEARCH";
